version: "3.9"
services:
  app1:
    build:
      context: .
      dockerfile: Dockerfile_app1
    ports:
     - "80:80"
  app2:
    build:
      context: .
      dockerfile: Dockerfile_app2
    ports:
     - "4080:80"
